import type { CampaignStatus } from "./CampaignStatus";

/**
 * Represents a marketing campaign tracked by Faith Harbor OS.
 */
export interface CampaignRecord {
  id: string;

  /**
   * Client this campaign is run for, if any.
   * Undefined for Faith Harbor's own campaigns.
   */
  clientId?: string;

  /**
   * Campaign name.
   */
  name: string;

  /**
   * Channel (for example "Email", "Facebook", "Google", "SEO").
   */
  channel?: string;

  /**
   * Current lifecycle state.
   */
  status: CampaignStatus;

  /**
   * Target audience description.
   */
  audience?: string;

  /**
   * Planned budget.
   */
  budget?: number;

  /**
   * Actual spend to date.
   */
  spend?: number;

  /**
   * Leads generated by the campaign.
   */
  leads?: number;

  /**
   * Campaign dates.
   */
  startDate?: string;
  endDate?: string;

  /**
   * Person responsible for the campaign.
   */
  owner?: string;

  /**
   * Internal notes.
   */
  notes?: string;

  /**
   * Extensible metadata.
   */
  metadata?: Record<string, unknown>;

  /**
   * Audit timestamps.
   */
  createdAt: string;
  updatedAt: string;
}
